CLASS zcl_02_contract_logali DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    CLASS-DATA currency TYPE c LENGTH 3.
  PROTECTED SECTION.
    DATA creation_date TYPE sydate.
  PRIVATE SECTION.
    DATA client TYPE string.
ENDCLASS.



CLASS zcl_02_contract_logali IMPLEMENTATION.
ENDCLASS.
